# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from orrb.protos import RenderService_pb2 as orrb_dot_protos_dot_RenderService__pb2


class RenderServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RenderBatch = channel.unary_unary(
        '/orrb.RenderService/RenderBatch',
        request_serializer=orrb_dot_protos_dot_RenderService__pb2.RenderBatchRequest.SerializeToString,
        response_deserializer=orrb_dot_protos_dot_RenderService__pb2.RenderBatchResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/orrb.RenderService/Update',
        request_serializer=orrb_dot_protos_dot_RenderService__pb2.UpdateRequest.SerializeToString,
        response_deserializer=orrb_dot_protos_dot_RenderService__pb2.UpdateResponse.FromString,
        )


class RenderServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RenderBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RenderBatch': grpc.unary_unary_rpc_method_handler(
          servicer.RenderBatch,
          request_deserializer=orrb_dot_protos_dot_RenderService__pb2.RenderBatchRequest.FromString,
          response_serializer=orrb_dot_protos_dot_RenderService__pb2.RenderBatchResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=orrb_dot_protos_dot_RenderService__pb2.UpdateRequest.FromString,
          response_serializer=orrb_dot_protos_dot_RenderService__pb2.UpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'orrb.RenderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
